### ISSUE TITLE
About target 250 gene list

### ISSUE THREAD

**Issue by winston52** [NEXGEM/TRIPLEX#2]
Hi,

Thanks for your excellent work. From your paper in the implementation details section: "We select 250 genes for each dataset following the criteria in [8]". Could you share the 250 complete gene list and how you got it? Thanks.

**Comment by winston52** [comment]
Hello, 

I have found npy files in your data. Could you share how you get the npy file for each dataset? In orther words, could you share how you get top 250 genes with high gene expression levels in each dataset?

**Comment by ymoneych** [comment]
Hi, 
thanks for your interest in our research. 

For each dataset, we calculated the average expression across all samples for each gene and selected the top 250 genes based on their expression. 

Let me know if you have any further questions.

**Comment by winston52** [comment]
Hi,

Thanks so much for your quickly reply. 

I wonder if you did some normalization before calculating the average expression value. As far as I'm concerned, you need to normalize the gene values across all the ST samples within a specific dataset before calculating the average expression value. And how did you get the parquet file? Could you share some brief ideas or code on how to get the parquet file(gene expression matrix file)?

Thank you.

**Comment by ymoneych** [comment]
Hi,

As we talked about before, we added up all the raw counts for each gene in each dataset and calculated the average expression based on those values.

The parquet file was saved in parquet format in Python, leaving only the expression amounts for the 250 genes selected from the entire matrix file.
