### ISSUE TITLE
About top 50 high predictive genes

### ISSUE THREAD

**Issue by winston52** [NEXGEM/TRIPLEX#3]
Hi,

Thanks for your excellent work. You mentioned in your paper "top 50 genes are determined based by on their average rank across all folds". Could you please clarify the selection of top 50 genes and provide more details? 

For the performance of the top 50 genes, did you train on the top 250 genes and then, during testing, only calculate the Pearson correlation for the top 50 genes? Could you share the relevent code regarding selecting top 50 genes?  Thank you.

**Comment by ymoneych** [comment]
Hi, thanks for your interest.

To select the top 50 genes, we performed cross-validation for each model in each dataset, ranked the predictive performance of genes in each fold, averaged the rankings across all folds, and selected the top 50 genes.

And what you said about evaluating the performance of the top 50 genes is correct. we trained on 250 genes and then calculated PCC on those 50 genes at the time of testing.
