### ISSUE TITLE
About the reproduction

### ISSUE THREAD

**Issue by Frances1996** [NEXGEM/TRIPLEX#4]
Thank you for your excellent work and for providing the code. I've encountered an issue during the reproduction process where it gets stuck in the Sanity Checking phase during training. Could you please explain what might be causing this?
The mode is set to be "cv", there is one GPU and I've set the strategy parameter of the PyTorch Lightning trainer to 'auto'.
The following is the output.
![微信截图_20240722092029](https://github.com/user-attachments/assets/d1366904-a3ef-4310-8900-4eb5152d3ac1)

**Comment by ymoneych** [comment]
Thank you for your interest in our research. 

Can you share the code you are using (related to Pytorch-lightning Trainer) and the specific error message so we can reproduce the error?

**Comment by Frances1996** [comment]
Hello.
Sorry for the late reply. I have now resolved the issue; it was caused by setting the num_worker too high. 
Thank you for your response!
