### ISSUE TITLE
About proprecess

### ISSUE THREAD

**Issue by Frances1996** [NEXGEM/TRIPLEX#6]
Hello.

I noticed that during training, gene data is preprocessed by dividing by the sum of the current point's gene expression values, followed by log normalization. For inference on unknown samples, how should we obtain the total sum of the predicted gene expression values?

Thank you for your assistance.

**Comment by ymoneych** [comment]
Hi, thank you for your interest in our work, and sorry for the late answer.

For training and test data with gene expression, we calculate the total count and normalize it. 

In our work, the model is trained using only normalized values during the training process, so the predicted values are assumed to be normalized values, and we do not perform additional normalization when inferring unknown samples.

If you have any further questions or comments, please let us know.

**Comment by Frances1996** [comment]
I understand, thanks for your reply!
